---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: start-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: start
  template:
    metadata:
      labels:
        app: start
    spec:
      containers:
        - name: start-app
          image: gcr.io/cf-spring-boot/initializr-k8s-image@sha256:15b2d48d5ab9fb3fe9077bb41faa5830cb13609b178ed65b23a49dfd28e54b34
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
          volumeMounts:
            - name: elastic
              mountPath: "/etc/config/initializr/stats/elastic"
              readOnly: true
          env:
            - name: SERVER_SHUTDOWN
              value: graceful
            - name: SPRING_CONFIG_IMPORT
              value: configtree:/etc/config/
      volumes:
        - name: elastic
          secret:
            secretName: elastic