---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: start-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: start
  template:
    metadata:
      labels:
        app: start
    spec:
      containers:
        - name: start-app
          image: gcr.io/cf-spring-boot/initializr-k8s-image@sha256:c169404f1c5f5abbf4932c5ceea62b145cc8e8a66df1f5d2c10587c13488c8d8
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
          volumeMounts:
            - name: elastic
              mountPath: "/etc/config/initializr/stats/elastic"
              readOnly: true
          env:
            - name: SERVER_SHUTDOWN
              value: graceful
            - name: SPRING_CONFIG_IMPORT
              value: configtree:/etc/config/
      volumes:
        - name: elastic
          secret:
            secretName: elastic