---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: start-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: start
  template:
    metadata:
      labels:
        app: start
    spec:
      containers:
        - name: start-app
          image: gcr.io/cf-spring-boot/initializr-k8s-image@sha256:9fab3fac66d46a6df5ea151e88a9583d043ad42082b8d7e26f6c57320688e8fd
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
          env:
            - name: SERVER_SHUTDOWN
              value: graceful
            - name: INITIALIZR_STATS_ELASTIC_URI
              valueFrom:
                secretKeyRef:
                  name: elastic
                  key: uri